### ISSUE TITLE
support for artifact bundles

### ISSUE THREAD

**Issue by aroman** [robertcepa/toucan-js#170]
It seems that Sentry has deprecated the release-based sourcemap uploading system used by toucan-js, and instead switched to a new system called ["artifact bundles"](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/artifact-bundles/).

Unfortunately, it seems that toucan doesn't support this system yet.

At minimum (but I believe there is more to do as well), it looks like [we need to use sentry version `7.47.0`](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#verify-your-source-files-contain-debug-id-injection-snippets-1) — this library is currently using `7.43.0`.

Is this something you plan to support?

**Comment by robertcepa** [comment]
All dependencies are now at 7.60.0

https://github.com/robertcepa/toucan-js/releases/tag/toucan-js%403.2.0

I'll look at Artifact Bundles sometimes next week, but any feedback/suggestions are welcome!

**Comment by huw** [comment]
I’ve got it working with artifact bundles on the server:

```js
import { $, argv } from "zx";

// Cut a Sentry release
const version = await $`pnpm sentry-cli releases propose-version`;
await $`sentry-cli releases new ${version}`;

// Inject & upload source maps for the server code
await $`pnpm sentry-cli sourcemaps inject ./dist/server`;
await $`pnpm sentry-cli sourcemaps upload --dist server --release ${version} ./dist/server`;

// Update the commit tracking on production
await $`pnpm sentry-cli releases set-commits ${version} --auto`;

await $`sentry-cli releases finalize ${version}`;

// Deploy to Cloudflare
// We need to add `--no-bundle` to prevent Wrangler from putting the build through ESBuild again, which will mess up the source mappings
await $`pnpm wrangler deploy --no-bundle --var SENTRY_VERSION:${version}`;

// Deploy the project in the current environment
await $`pnpm sentry-cli releases deploys ${version} new`;
```

Essentially, everything works like it used to, but you have to migrate a few of the commands to the new `sentry-cli sourcemaps` sub-command and add `sentry-cli sourcemaps inject` (unless you’re using the ESBuild plugin etc).

The one caveat is the trade-off between passing `--no-bundle` to Wrangler or not. If you decide to pass `--no-bundle`, you can inject & upload your source maps after your custom build and before the main worker upload. If you omit it, then you’ll have to set `wrangler deploy --outdir ./dist/wrangler` and upload your source maps from `sentry-cli sourcemaps inject ./dist/wrangler` after your deploy. _However_, in my experience the latter leaves my source maps slightly off (by one or two lines) and I didn’t have the time to figure out why.

**Comment by aroman** [comment]
Thanks for sharing, @huw. Here's what I've been doing via GitHub Actions. My trick has been to use `--dry-run`, then upload those sourcemaps. It's been working fine for us in production. I'm pretty sure this approach is using the deprecated release-based sourcemap uploading... but I do actually see "Artifact Bundles" in the sentry dashboard 🤷 

In your approach, how are you actually building your worker project? 

```yaml
- name: Generate server source maps
  run: npm run --workspace server deploy-production -- --dry-run --outdir=dist
- name: Create Sentry release for this commit
  run: npx sentry-cli releases new "$SENTRY_RELEASE"
- name: Upload client source maps to Sentry
  run: npx sentry-cli releases files "$SENTRY_RELEASE" upload-sourcemaps --dist client ./client/dist
- name: Upload server source maps to Sentry
  run: npx sentry-cli releases files "$SENTRY_RELEASE" upload-sourcemaps --dist server ./server/dist
- name: Set commits for Sentry release
  run: npx sentry-cli releases set-commits "$SENTRY_RELEASE" --commit "${{ github.repository }}@${{ github.event.before }}..${{ github.sha }}"
- name: Finalize sentry release
  run: npx sentry-cli releases finalize "$SENTRY_RELEASE"
```


<img width="826" alt="CleanShot 2023-08-01 at 13 45 46@2x" src="https://github.com/robertcepa/toucan-js/assets/531504/44e67a60-fbb1-48af-82cc-745223ed5f15">
